# id|popis
T01|Vytvoř uživatele testuser (včetně /home/testuser)
T02|Smaž uživatele olduser včetně jeho /home/olduser
T03|V /home/vivi/lab vytvoř file1.txt a napiš do něj přesně: LinuxTest
T04|Zkopíruj file1.txt do file2.txt a smaž soubor temp.txt v /home/vivi/lab
T05|Nastav práva: /home/vivi/lab má 0750 a file1.txt má 0640 a skupinu root
T06|Spusť sleep 9999 na pozadí, ulož jeho PID do /home/vivi/lab/sleep.pid a pak ho ukonči přes kill
T07|Vytvoř archiv /home/vivi/lab-archive.tar.xz z adresáře /home/vivi/lab
T08|Rozbal archiv do /home/vivi/extracted_lab tak, aby existoval /home/vivi/extracted_lab/lab/file1.txt
T09|Najdi soubor s názvem hidden_note.txt někde v /home/vivi/maze a zkopíruj ho do /home/vivi/found/
T10|Najdi pomocí grep řetězec SECRET123 v /home/vivi/maze a ulož cestu souboru do /home/vivi/grep_result.txt
T11|Vytvoř skupinu project, přidej do ní testuser a nastav /home/vivi/lab na group project s právy 770
T12|Změň heslo uživateli testuser
T13|Nainstaluj Midnight Commander (mc)
T15|Vytvoř /home/vivi/lab/date.txt pomocí příkazu date ve formátu DD.MM.RRRR HH:MM:SS
